### ISSUE TITLE
A question about the history of TS

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#122]
Was this a spin-off of mklauber's TS?

I was just thinking it might be gook to remove the original from the community reference documentation if this is the replacement.

Thanks!

**Comment by Arlen22** [comment]
Yes it was. I sent him an email asking permission to use the name, and he was fine with that, so we callled it TiddlyServer 2.0. He posted an email then stating that he was discontinuing his support for version one, as my system accomplished the same end goal that his had, which was multiple node TiddlyWikis on the same port. 

That's part of the reason that I haven't followed the same path as Jed when he made Bob, because he makes a few assumptions and writes to data folders directly, whereas TiddlyServer instantiates a fully working Node TiddlyWiki server and client (with a couple exceptions). 

I have tried to think through ways in which we could make the server side leaner on memory or write directly to datafolders, but that is outside the scope of TiddlyServer. So this is not a direct competitor or a replacement for Jed's system. But it is the direct version 2.0 of mklauber's TiddlyServer, so that should be removed from the docs.

**Comment by Marxsal** [comment]
Thanks for your reply!

I was asking because I was thinking that Matt's reference on TiddlyWiki.com should either be removed or have a deprecation notice. Same for links.tiddlywiki.com. But I wanted to be sure that you had taken over the _**same**_ tiddlyserver project (there are an awful lot of similarly named products within the TW world).
