### ISSUE TITLE
Supporting default and local configurations

### ISSUE THREAD

**Issue by inmysocks** [Arlen22/TiddlyServer#15]
I used some things from another project to modify tiddlyserver so that you have two configuration files instead of the single settings.json file currently used. The idea is that you have a default configuration file (called Config.json) that works and then a local settings file (Local.json) that can modify the default version.

So for tiddlyserver the default file would have default values for every property, but if someone wants to change the address on their version they edit Local.json to just add the address property, than this overrides the default value in Config.json without them having to edit any of the default values.

This way a person only has to set the options that they want to change from the default and TiddlyServer can have a default configuration that works without any configuration needed.

I am also working on creating a wiki that can be the default location for navigation and that will let you change the settings without having to directly edit a json file. I will make another issue for that.

**Comment by inmysocks** [comment]
My fork uses this, you can see the relevant files here: https://github.com/OokTech/TiddlyServer/tree/master/config

If you want to use this than I can submit a pull request.

**Comment by Arlen22** [comment]
The defaults are already baked into the code except for the tree property. So technically that is all you would need. But I like to include everything to make it obvious what is available. 

Thoughts?

**Comment by inmysocks** [comment]
Having everything listed is a good idea. The way I use this with the robot is I have the default configuration list every possible option with the default value so you can reference that configuration if you need to know what options there are.

The reason I have two files is you can have a local configuration file that isn't tracked by git, that way you can have multiple deployments of the code and each can have their own settings and if a default needs to be changed, or if some new setting is added as part of a code update, all you need to do is pull from the repo and you don't have to do anything to update the configuration and you don't lose any settings you have.

Part of the idea is that if this is combined with a configuration utility than errors in the configuration will just fall back to the default and you can fix the problems using the utility instead of the code just failing, but if you want to just have the defaults hardcoded that would do the same thing. My only concern with that it is harder to find what all the default values are that way.

**Comment by Arlen22** [comment]
`settings.json` is in the list of ignored files on the TiddlyServer repo. I normally run directly off of master when I use TiddlyServer, so I do have a `settings.json` file in the folder. One thing you could do is tell people to make a copy of `example-settings.json` called `settings.json` instead of just renaming it. 

I'm just a little bit afraid of setting any defaults for the tree in the program. If something doesn't work right, I don't want to be serving files the user isn't aware of.

**Comment by Arlen22** [comment]
As far as the server crashing if the configuration is not correct, which would affect #16, I can set it up so that it will still serve `/admin` on `localhost:8080` or whatever port is specified via command line in case the configuration somehow gets messed up. But the server will also have to validate the configuration before saving it anyway, so this should not be much of a problem.

Does this work for your use case? If not, I am open to considering other options. I don't like to fall back on defaults too much if a config is corrupted or doesn't parse correctly, but I don't mind having a default setup for keys that are not specified. Which is how I already have it set up. As I mentioned before, only tree is required.
