### ISSUE TITLE
Opening into a wiki instead of the html listing

### ISSUE THREAD

**Issue by inmysocks** [Arlen22/TiddlyServer#16]
I am working on making a wiki that can be used to configure tiddlyserver. My hope is that using the default configuration settings from #15, when you start tiddlyserver and open up 127.0.0.1:8080 it will open into a wiki that will guide you through setting up tiddlyserver.

I have almost all of the pieces of this from other projects so it is just a matter of putting the pieces together in a nice way.

My work on this is on my fork here: https://github.com/OokTech/TiddlyServer

**Comment by Arlen22** [comment]
This sounds like a possibility, although I'm not sure if a wiki is really necessary. I would sooner implement something in AngularJS since that is a lot easier to use when it comes to dynamic forms and server APIs. However, if you get it together I will definitely take a look at it. 

My only question is how are you planning to sync it to the server. I can add the endpoint to the server. The admin path is reserved for this type of stuff, so we could do `/admin/settings.json`. 

I don't have the time to dive into TiddlyWiki to implement the wiki, so if you take care of that part, I can take care of the server part. To prevent CSRF attacks, use a PUT request and add the `X-Requested-With: XMLHTTPRequest` header.

Also, I am able to restrict this to only requests coming in on localhost. So that will help security quite a bit, as network devices would not be able to access it, as I understand it.

**Comment by inmysocks** [comment]
I will make a widget to do a put request like that. 

For now I am going to put the wiki together and just have it listed as part of the tree. I think that it would be nice to be able to set what gets opened when you go to the base url (e.g., 127.0.0.1:8080 can bring you to a wiki instead of the tree explorer) but I think that is very low priority.

**Comment by Arlen22** [comment]
Sounds good. I can also mount the wiki at `/admin` or somewhere like that. Let me know when you have it ready. This seems like a good idea.

**Comment by Arlen22** [comment]
Version 2.1 now supports the indexPath property for group elements. More details are coming in the documentation I will be posting for version 2.1.
