### ISSUE TITLE
Can I pass in lazy-loading settings?

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#58]
Can I pass in lazy-loading settings, either on the command line or in the settings.json file?

Thanks!
Mark

**Comment by Arlen22** [comment]
There might be the possibility of changing the settings for each request, but this has some inconsistencies. It is also possible to modify server.js to provide custom settings or async wait on other things before starting. But lazy-loading, as we're familiar with the term in TiddlyWiki, would not really work, because all settings must be available in order to handle requests.
