### ISSUE TITLE
Edition server is deprecated and listen should be used

### ISSUE THREAD

**Issue by NoxMortem** [Arlen22/TiddlyServer#69]
node tiddlywiki.js --editions
```
* server: Provides an HTTP server interface to TiddlyWiki (deprecated in favour of the new listen command
* listen: Provides an HTTP server interface to TiddlyWiki
```

**Comment by Arlen22** [comment]
I can't find this output for some reason in 5.1.20. Maybe it was removed, because the editions folder is completely identical for both commands. You're correct that the listen command is the correct command to use, but there is no listen edition in the current TiddlyWiki master. https://github.com/Jermolene/TiddlyWiki5/tree/master/editions
